import { LocalLlmRouter } from './llm-provider.js';

const landmarks = [
  {id:'njp',name:'New Jalpaiguri',short:'The mountain journey begins',distance:'at the starting point',built:'1964',known:'Gateway to the hills',altitude:'390 ft',progress:0,coords:[26.6827,88.4457],insight:'Your narrow-gauge journey begins on the plains before it starts its remarkable climb into the Himalayan foothills.'},
  {id:'sukna',name:'Sukna Forest',short:'Where the railway enters the foothills',distance:'within 300 m',built:'1880s',known:'Forest & steep gradient',altitude:'500 ft',progress:15,coords:[26.842,88.384],insight:'Beyond Sukna, the line leaves the plains and begins threading through sal forest towards the mountains.'},
  {id:'tindharia',name:'Tindharia',short:'The railway’s engineering heart',distance:'within 240 m',built:'1881',known:'Historic workshop',altitude:'2,820 ft',progress:36,coords:[26.879,88.304],insight:'This is where the DHR’s workshop has kept its famous little locomotives and rolling stock alive for generations.'},
  {id:'kurseong',name:'Kurseong',short:'The town of white orchids',distance:'within 120 m',built:'1880',known:'Hill station & tea',altitude:'4,864 ft',progress:52,coords:[26.882,88.278],insight:'Kurseong is a cool hill town where the railway shares the street with everyday life, tea gardens, and mist.'},
  {id:'batasia',name:'Batasia Loop',short:'A graceful spiral beneath Kanchenjunga',distance:'within 180 m',built:'1919',known:'A full 360° loop',altitude:'6,700 ft',progress:72,coords:[26.7284,88.2543],insight:'The railway spirals through a garden to gain height gracefully — with Kanchenjunga watching over the curve.'},
  {id:'ghum',name:'Ghum Station',short:'India’s highest railway station',distance:'within 95 m',built:'1881',known:'India’s highest station',altitude:'7,407 ft',progress:82,coords:[26.733,88.263],insight:'At 7,407 feet, Ghum is India’s highest railway station and one of the most atmospheric pauses on the route.'},
  {id:'darjeeling',name:'Darjeeling',short:'The railway’s hill-top finale',distance:'at the destination',built:'1881',known:'Toy Train terminus',altitude:'6,700 ft',progress:100,coords:[27.036,88.262],insight:'You have reached Darjeeling, where a mountain railway built for transport became a living heritage experience.'}
];
const DB_NAME='dhr-companion-local-rag', DB_VERSION=1, VECTOR_SIZE=128;
const ALIASES={circle:'loop',circular:'loop',spiral:'loop',turn:'loop',zigzag:'reverse',zigzags:'reverse',backtrack:'reverse',climbing:'climb',ascend:'climb',ascent:'climb',engine:'locomotive',engines:'locomotive',steam:'locomotive',tracks:'track',train:'railway',heritage:'unesco',worldheritage:'unesco',museum:'ghum',highest:'ghum'};
const state={location:landmarks.find(item=>item.id==='batasia'),mode:'demo',documents:[],geoWatch:null,llm:null,aiLabel:'Preparing local AI',locationDistance:null};
const $=selector=>document.querySelector(selector);
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

class RagStore {
  constructor(db){this.db=db;}
  static open(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('documents'))db.createObjectStore('documents',{keyPath:'id'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'});};request.onsuccess=()=>resolve(new RagStore(request.result));request.onerror=()=>reject(request.error);});}
  object(name,mode='readonly'){return this.db.transaction(name,mode).objectStore(name);}
  getMeta(key){return new Promise((resolve,reject)=>{const request=this.object('meta').get(key);request.onsuccess=()=>resolve(request.result?.value);request.onerror=()=>reject(request.error);});}
  all(){return new Promise((resolve,reject)=>{const request=this.object('documents').getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error);});}
  async seedIfNeeded(corpus){if(await this.getMeta('corpusVersion')===corpus.version)return this.all();return new Promise((resolve,reject)=>{const tx=this.db.transaction(['documents','meta'],'readwrite');tx.objectStore('documents').clear();corpus.documents.forEach(doc=>tx.objectStore('documents').put({...doc,embedding:embed(`${doc.title}. ${doc.text}`),indexedAt:Date.now()}));tx.objectStore('meta').put({key:'corpusVersion',value:corpus.version});tx.oncomplete=async()=>resolve(await this.all());tx.onerror=()=>reject(tx.error);});}
}

function canonicalTokens(text){return String(text).toLowerCase().match(/[a-z0-9]+/g)?.map(token=>ALIASES[token]||token)||[];}
function hash(value){let h=2166136261;for(let i=0;i<value.length;i+=1){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function embed(text){const vector=new Float32Array(VECTOR_SIZE);canonicalTokens(text).forEach(token=>{const h=hash(token);vector[h%VECTOR_SIZE]+=(h&1)?1:-1;for(let i=0;i<token.length-2;i+=1){const gram=hash(token.slice(i,i+3));vector[gram%VECTOR_SIZE]+=(gram&1)?.18:-.18;}});const length=Math.sqrt(vector.reduce((sum,value)=>sum+value*value,0))||1;return Array.from(vector,value=>value/length);}
function cosine(a,b){let score=0;for(let i=0;i<a.length;i+=1)score+=a[i]*b[i];return score;}
function geoBias(doc,location){if(doc.landmarks.includes(location.id))return .24;const closest=Math.min(...doc.landmarks.map(id=>landmarks.find(item=>item.id===id)?.progress??50));return Math.max(0,.1-Math.abs(closest-location.progress)/400);}
function retrieve(question,limit=3){const query=embed(question);return state.documents.map(doc=>({...doc,semanticScore:cosine(query,doc.embedding),locationScore:geoBias(doc,state.location)})).map(doc=>({...doc,score:doc.semanticScore*.8+doc.locationScore*.2})).sort((a,b)=>b.score-a.score).slice(0,limit);}

function updateAiStatus(status){state.aiLabel=status.label;const badge=$('#aiRuntimeStatus');if(badge)badge.textContent=status.kind==='model'?`✦ ${status.label}`:`⌁ ${status.label}`;const storage=$('#storageStatus');if(storage)storage.textContent=`${state.documents.length||'…'} facts · IndexedDB · ${status.kind==='model'?'Gemma local':'local RAG'}`;}
function renderSuggestions(){const choices=state.location.id==='batasia'?['Why does the train loop here?','How does a Z-reverse work?','What can I see from here?','Why is this UNESCO heritage?']:[`What is special about ${state.location.name}?`,'Why was this railway built?','Tell me about the locomotives','Why is the track so narrow?'];$('#suggestions').innerHTML=choices.map(choice=>`<button class="suggestion">${choice}</button>`).join('');document.querySelectorAll('.suggestion').forEach(button=>button.addEventListener('click',()=>ask(button.textContent)));}
function renderLocation({showToast=true}={}){const loc=state.location;$('#locationTitle').textContent=`You’re near ${loc.name}`;$('#locationInsight').textContent=loc.insight;$('#distanceLabel').textContent=state.locationDistance===null?loc.distance:`${Math.round(state.locationDistance)} m away`;$('#contextName').textContent=loc.name;$('#contextBuilt').textContent=loc.built;$('#contextKnown').textContent=loc.known;$('#contextAltitude').textContent=loc.altitude;$('#journeyPercent').textContent=`${loc.progress}%`;$('#altitude').textContent=loc.altitude;renderSuggestions();renderMap();if(showToast){$('#toastTitle').textContent=`🚂 You’re near ${loc.name}`;$('#toastText').textContent=loc.short;$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),6500);}}
function addMessage(text,kind='guide',sources=[]){const article=document.createElement('article');article.className=`message ${kind==='user'?'user-message':'guide-message'}`;const provenance=sources.length?`<small class="source-line">Grounded in ${sources.map(source=>escapeHTML(source.title)).join(' · ')}</small>`:'';article.innerHTML=kind==='user'?`<p>${escapeHTML(text)}</p>`:`<div class="guide-face">D</div><div><span class="message-label">${escapeHTML(state.aiLabel).toUpperCase()} · OFFLINE</span><p>${escapeHTML(text)}</p>${provenance}</div>`;$('#conversation').append(article);$('#conversation').scrollTop=$('#conversation').scrollHeight;}
async function ask(question){const clean=question.trim();if(!clean)return;$('#questionInput').value='';addMessage(clean,'user');const sources=retrieve(clean);const thinking=document.createElement('article');thinking.className='message guide-message';thinking.innerHTML='<div class="guide-face">D</div><div><span class="message-label">LOCAL SEMANTIC RETRIEVAL</span><p>Searching on-device heritage notes…</p></div>';$('#conversation').append(thinking);try{const answer=await state.llm.answer({question:clean,location:state.location,sources});thinking.remove();addMessage(answer,'guide',sources);}catch(_){thinking.remove();addMessage('The local model could not complete that answer. The heritage library is still available offline; try again or choose a suggested question.','guide',sources);}}
function renderMap(){const board=$('#mapBoard');if(!board)return;board.innerHTML=landmarks.map((loc,index)=>`<div class="map-stop"><small>${String(index+1).padStart(2,'0')}</small><button class="${loc.id===state.location.id?'active':''}" data-location="${loc.id}"><strong>${loc.name}</strong><br/><span>${loc.short}</span></button><small>${loc.altitude}</small></div>`).join('');board.querySelectorAll('[data-location]').forEach(button=>button.addEventListener('click',()=>selectLocation(button.dataset.location)));}
function selectLocation(id,showToast=true,distance=null){state.location=landmarks.find(item=>item.id===id)||state.location;state.locationDistance=distance;renderLocation({showToast});document.querySelectorAll('.location-choice').forEach(button=>button.classList.toggle('active',button.dataset.location===id));}
function renderLocationOptions(){$('#locationOptions').innerHTML=landmarks.map(loc=>`<button class="location-choice ${loc.id===state.location.id?'active':''}" data-location="${loc.id}">${loc.name}<small> · ${loc.altitude}</small></button>`).join('');document.querySelectorAll('.location-choice').forEach(button=>button.addEventListener('click',()=>{state.mode='demo';selectLocation(button.dataset.location);}));}
function nearestLandmark(position){const {latitude,longitude}=position.coords;const distance=([a,b])=>Math.hypot((a-latitude)*111000,(b-longitude)*111000*Math.cos(latitude*Math.PI/180));return landmarks.map(loc=>({loc,distance:distance(loc.coords)})).sort((a,b)=>a.distance-b.distance)[0];}
function useGPS(){if(!navigator.geolocation){$('#gpsNote').textContent='GPS is unavailable in this browser. Simulation mode is still fully active.';return;}$('#gpsNote').textContent='Looking for your position…';const apply=position=>{const nearest=nearestLandmark(position);state.mode='gps';const changed=nearest.loc.id!==state.location.id;selectLocation(nearest.loc.id,changed,nearest.distance);$('#gpsNote').textContent=`GPS active. Nearest curated landmark: ${nearest.loc.name} (${Math.round(nearest.distance)} m away).`;};navigator.geolocation.getCurrentPosition(apply,()=>$('#gpsNote').textContent='We could not access GPS. Simulation mode remains ready for your journey.',{enableHighAccuracy:true,timeout:7000,maximumAge:30000});if(state.geoWatch!==null)navigator.geolocation.clearWatch(state.geoWatch);state.geoWatch=navigator.geolocation.watchPosition(apply,()=>{},{enableHighAccuracy:true,maximumAge:30000});}
function showView(view){['companion','journey','library'].forEach(name=>$(`#${name}View`).classList.toggle('hidden',name!==view));document.querySelectorAll('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.nav===view));if(view==='journey')renderMap();if(view==='library')$('#libraryGrid').innerHTML=state.documents.map(item=>`<article class="library-item"><p class="eyebrow">INDEXEDDB · VECTOR READY</p><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.text)}</p></article>`).join('');}
async function loadCorpus(){const response=await fetch('./data/dhr-knowledge.json');if(!response.ok)throw new Error('Local heritage data is unavailable');const corpus=await response.json();const store=await RagStore.open();state.documents=await store.seedIfNeeded(corpus);$('#factCount').textContent=state.documents.length;}
async function init(){try{await loadCorpus();}catch(_){$('#factCount').textContent='0';$('#gpsNote').textContent='Local library setup needs one successful app load before offline use.';}renderLocation({showToast:false});renderLocationOptions();state.llm=new LocalLlmRouter({embed,onStatus:updateAiStatus});updateAiStatus({kind:'loading',label:'Starting local AI'});await state.llm.initialize();
  $('#askForm').addEventListener('submit',event=>{event.preventDefault();ask($('#questionInput').value);});$('#tellMeButton').addEventListener('click',()=>ask(`Tell me more about ${state.location.name}`));$('#learnButton').addEventListener('click',()=>ask(`What is special about ${state.location.name}?`));$('#dismissToast').addEventListener('click',()=>$('#toast').classList.add('hidden'));$('#settingsButton').addEventListener('click',()=>$('#settingsModal').classList.remove('hidden'));document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$('#settingsModal').classList.add('hidden')));$('#settingsModal').addEventListener('click',event=>{if(event.target===$('#settingsModal'))$('#settingsModal').classList.add('hidden')});
  document.querySelectorAll('.mode-choice').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.mode-choice').forEach(choice=>choice.classList.toggle('active',choice===button));if(button.dataset.mode==='gps')useGPS();else{state.mode='demo';if(state.geoWatch!==null)navigator.geolocation?.clearWatch(state.geoWatch);state.geoWatch=null;state.locationDistance=null;$('#gpsNote').textContent='Simulation is active. Retrieval is biased to the selected landmark.';}}));
  $('#gemmaFile').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;$('#modelNote').textContent='Loading the Gemma model on this device…';try{await state.llm.loadGemmaFile(file);$('#modelNote').textContent='Gemma is now loaded locally. No prompt or location data is sent to a server.';}catch(_){$('#modelNote').textContent='The model runtime is not installed or this model is incompatible. Local RAG remains active.';}});
  $('#mapButton').addEventListener('click',()=>showView('journey'));document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.nav)));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTimeout(()=>{$('#toast').classList.remove('hidden');window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),6500);},850);}
document.addEventListener('DOMContentLoaded',init);
